# Generated by Django 5.0.7 on 2024-07-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Special', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.AddField(
            model_name='special_meal',
            name='cook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cook'),
        ),
    ]
