# Generated by Django 5.0.7 on 2024-07-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Special', '0002_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Special_Meal',
            new_name='SpecialMeal',
        ),
    ]
