# Generated by Django 5.0.7 on 2024-07-13 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='AboutChef',
            new_name='AboutUs',
        ),
        migrations.RemoveField(
            model_name='mainfood',
            name='cook',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='cook',
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cook')),
            ],
        ),
        migrations.DeleteModel(
            name='Appetiser',
        ),
        migrations.DeleteModel(
            name='MainFood',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
    ]
